// Suíte funcional do Revela: cada teste é independente e registra passou/falhou com detalhe.
const { chromium } = require('playwright'); const fs = require('fs'); const path = require('path');
const SP = process.argv[2], URL = process.argv[3] || 'http://localhost:8765/index.html', ONLY = process.argv[4] || '';
const EXE = process.env.USERPROFILE + '/AppData/Local/ms-playwright/chromium_headless_shell-1234/chrome-headless-shell-win64/chrome-headless-shell.exe';
const OUT = SP + '/outs'; fs.mkdirSync(OUT, { recursive: true });
const R = []; let errs = [];
const sleep = ms => new Promise(r => setTimeout(r, ms));
function rec(group, name, ok, info) { R.push({ group, name, ok, info: info || '' }); console.log((ok ? 'OK   ' : 'FALHA') + ' [' + group + '] ' + name + (info ? ' — ' + info : '')); }
async function T(group, name, fn) {
  const e0 = errs.length;
  try { const info = await fn(); const ne = errs.slice(e0); if (ne.length) rec(group, name, false, (info || '') + ' | erro JS: ' + ne[0].slice(0, 160)); else rec(group, name, true, info); }
  catch (e) { rec(group, name, false, String(e.message || e).split('\n')[0].slice(0, 220) + (errs.length > e0 ? ' | erro JS: ' + errs[e0].slice(0, 120) : '')); }
}
const assert = (c, msg) => { if (!c) throw new Error(msg); };
function hook(p) { p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (m.type() === 'error' && !/TensorFlow|GL Driver|gl_context|favicon/.test(m.text())) errs.push('console: ' + m.text()); }); }
const sig = p => p.evaluate(() => { const v = document.getElementById('view'), c = document.createElement('canvas'); c.width = 24; c.height = 24; const x = c.getContext('2d'); x.drawImage(v, 0, 0, 24, 24); return { w: v.width, h: v.height, d: Array.from(x.getImageData(0, 0, 24, 24).data) }; });
const sigEl = (p, sel) => p.evaluate(sel => { const el = document.querySelector(sel), c = document.createElement('canvas'); c.width = 240; c.height = 240; const x = c.getContext('2d'); x.imageSmoothingQuality = 'high'; x.drawImage(el, 0, 0, 240, 240); const d = x.getImageData(0, 0, 240, 240).data, out = []; for (let by = 0; by < 24; by++) for (let bx = 0; bx < 24; bx++) { let r = 0, g = 0, b = 0; for (let y = 0; y < 10; y++) for (let xx = 0; xx < 10; xx++) { const i = ((by * 10 + y) * 240 + bx * 10 + xx) * 4; r += d[i]; g += d[i + 1]; b += d[i + 2]; } out.push(r / 100, g / 100, b / 100, 255); } return { d: out }; }, sel);
const diff = (a, b) => { let s = 0; for (let i = 0; i < a.d.length; i += 4) s += Math.abs(a.d[i] - b.d[i]) + Math.abs(a.d[i + 1] - b.d[i + 1]) + Math.abs(a.d[i + 2] - b.d[i + 2]); return s / (a.d.length / 4 * 3); };
const setRange = (p, sel, v) => p.evaluate(([sel, v]) => { const e = document.querySelector(sel); if (!e) throw new Error('sem controle ' + sel); e.value = v; e.dispatchEvent(new Event('input', { bubbles: true })); return +e.value; }, [sel, v]);
async function ready(p) { await p.goto(URL); await sleep(6500); await p.waitForFunction(() => /pronta|indispon/.test(document.getElementById('segStat').textContent), null, { timeout: 90000 }); }
async function open(p, file, nameOverride) {
  const nm = nameOverride || (typeof file === 'string' ? path.basename(file) : file.name);
  await p.setInputFiles('#file', file);
  await p.waitForFunction(n => document.getElementById('capName').textContent === n && document.getElementById('view').width > 30, nm, { timeout: 40000 });
  await sleep(400); await p.waitForFunction(() => document.getElementById('aiPill').hidden, null, { timeout: 180000 }); await sleep(2600);
}
const tab = (p, t) => p.click('.tabbtn[data-tab=' + t + ']');
async function tool(p, id) { await tab(p, 'ferramentas'); if (await p.isVisible('#toolBack')) await p.click('#toolBack'); await p.click('.tool[data-tool=' + id + ']'); await sleep(250); }
async function extraTool(p, name) { await tab(p, 'ferramentas'); if (await p.isVisible('#toolBack')) await p.click('#toolBack'); await p.click('.tool:has-text("' + name + '")'); await sleep(250); }
const synth = (p, w, h, kind, type) => p.evaluate(([w, h, kind, type]) => {
  const c = document.createElement('canvas'); c.width = w; c.height = h; const x = c.getContext('2d');
  if (kind === 'alpha') { x.clearRect(0, 0, w, h); x.fillStyle = 'rgba(200,60,40,.8)'; x.beginPath(); x.arc(w / 2, h / 2, Math.min(w, h) / 3, 0, 7); x.fill(); }
  else if (kind === 'gray') { const g = x.createLinearGradient(0, 0, w, h); g.addColorStop(0, '#222'); g.addColorStop(1, '#ddd'); x.fillStyle = g; x.fillRect(0, 0, w, h); x.fillStyle = '#777'; x.fillRect(w * 0.3, h * 0.3, w * 0.4, h * 0.4); }
  else if (kind === 'quad') { x.fillStyle = '#d33'; x.fillRect(0, 0, w / 2, h / 2); x.fillStyle = '#3d3'; x.fillRect(w / 2, 0, w / 2, h / 2); x.fillStyle = '#33d'; x.fillRect(0, h / 2, w / 2, h / 2); x.fillStyle = '#dd3'; x.fillRect(w / 2, h / 2, w / 2, h / 2); }
  else { const g = x.createLinearGradient(0, 0, 0, h); g.addColorStop(0, '#7fa6d8'); g.addColorStop(0.55, '#d9c9a8'); g.addColorStop(1, '#5a7a3a'); x.fillStyle = g; x.fillRect(0, 0, w, h); for (let i = 0; i < 400; i++) { x.fillStyle = `hsl(${(i * 37) % 360},50%,${30 + (i % 40)}%)`; x.fillRect((i * 97) % w, h * 0.6 + (i * 53) % (h * 0.4), w / 60, h / 40); } }
  return c.toDataURL(type || 'image/jpeg', 0.9).split(',')[1];
}, [w, h, kind, type]);
function withExif(buf, orientation) {
  const ex = Buffer.from([0xFF, 0xE1, 0x00, 0x22, 0x45, 0x78, 0x69, 0x66, 0x00, 0x00, 0x49, 0x49, 0x2A, 0x00, 0x08, 0x00, 0x00, 0x00, 0x01, 0x00, 0x12, 0x01, 0x03, 0x00, 0x01, 0x00, 0x00, 0x00, orientation, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]);
  return Buffer.concat([buf.subarray(0, 2), ex, buf.subarray(2)]);
}
const want = g => !ONLY || ONLY.split(',').includes(g);

(async () => {
  const b = await chromium.launch({ executablePath: EXE });
  const PORT = SP + '/pexels/retrato_mulher.jpg', LAND = SP + '/pexels/montanha.jpg', CASAL = SP + '/pexels2/r2_10.jpg';

  // ---------- G1: início e abertura de arquivos ----------
  if (want('G1')) {
    const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 }, acceptDownloads: true }); const p = await ctx.newPage(); hook(p); await ready(p);
    await T('G1', 'tela inicial com os 3 botões', async () => { for (const id of ['camBtn', 'galBtn', 'exBtn']) assert(await p.isVisible('#' + id), 'falta ' + id); });
    await T('G1', 'salvar sem foto avisa', async () => { await p.click('#saveBtn'); await sleep(300); const t = await p.innerText('#toast'); assert(/Abra uma foto/.test(t), 'aviso: ' + t); });
    await T('G1', 'foto de exemplo abre', async () => { await p.click('#exBtn'); await p.waitForFunction(() => document.getElementById('view').width > 100, null, { timeout: 20000 }); await sleep(300); await p.waitForFunction(() => document.getElementById('aiPill').hidden, null, { timeout: 120000 }); assert(await p.isHidden('#start'), 'tela inicial continua visível'); });
    await T('G1', 'JPEG de retrato: automático completa', async () => { await open(p, PORT); const h = await p.innerText('#heroT'); const n = await p.locator('#notes li').count(); assert(/IA Revela/.test(h) && n > 2, 'hero=' + h + ' notas=' + n); return h; });
    await T('G1', 'PNG com transparência', async () => { const d = await synth(p, 800, 600, 'alpha', 'image/png'); await open(p, { name: 'alpha.png', mimeType: 'image/png', buffer: Buffer.from(d, 'base64') }); const s = await sig(p); return 'cantos rgb ' + s.d.slice(0, 3).join(','); });
    await T('G1', 'foto em tons de cinza', async () => { const d = await synth(p, 900, 600, 'gray'); await open(p, { name: 'cinza.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(d, 'base64') }); const s = await sig(p); let mx = 0; for (let i = 0; i < s.d.length; i += 4) mx = Math.max(mx, Math.abs(s.d[i] - s.d[i + 1]), Math.abs(s.d[i + 1] - s.d[i + 2])); assert(mx < 14, 'ganhou cor: diferença entre canais ' + mx); return 'dif. máx. entre canais ' + mx; });
    await T('G1', 'foto minúscula 40×30', async () => { const d = await synth(p, 40, 30, 'land'); await open(p, { name: 'mini.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(d, 'base64') }); return await p.innerText('#capSize'); });
    await T('G1', 'foto enorme 6000×4000', async () => { const d = await synth(p, 6000, 4000, 'land'); const t0 = Date.now(); await open(p, { name: 'enorme.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(d, 'base64') }); const s = await p.innerText('#capSize'); assert(/3000 × 2000/.test(s), 'tamanho ' + s); return s + ' em ' + (Date.now() - t0) + ' ms'; });
    await T('G1', 'panorâmica 3000×500', async () => { const d = await synth(p, 3000, 500, 'land'); await open(p, { name: 'pano.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(d, 'base64') }); return await p.innerText('#capSize'); });
    await T('G1', 'vertical extrema 500×3000', async () => { const d = await synth(p, 500, 3000, 'land'); await open(p, { name: 'alta.jpg', mimeType: 'image/jpeg', buffer: Buffer.from(d, 'base64') }); return await p.innerText('#capSize'); });
    await T('G1', 'EXIF de rotação é respeitado', async () => { const d = await synth(p, 300, 200, 'quad'); await open(p, { name: 'exif6.jpg', mimeType: 'image/jpeg', buffer: withExif(Buffer.from(d, 'base64'), 6) }); const s = await p.innerText('#capSize'); assert(/200 × 300/.test(s), 'tamanho ' + s + ' (esperado 200 × 300)'); return s; });
    await T('G1', 'arquivo que não é imagem dá aviso', async () => { await p.evaluate(() => { document.getElementById('toast').textContent = ''; }); await p.setInputFiles('#file', { name: 'nota.txt', mimeType: 'text/plain', buffer: Buffer.from('oi') }); await sleep(800); const t = await p.innerText('#toast'), c = await p.innerText('#capName'); assert(/imagem|arquivo/i.test(t), 'sem aviso ao usuário (toast="' + t + '", legenda="' + c + '")'); });
    await T('G1', 'JPEG corrompido dá aviso', async () => { await p.evaluate(() => { document.getElementById('toast').textContent = ''; }); await p.setInputFiles('#file', { name: 'ruim.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('nao sou jpeg de verdade 1234567890') }); await sleep(1200); const t = await p.innerText('#toast'), c = await p.innerText('#capName'); assert(/consegui|abrir/i.test(t), 'sem aviso em destaque (toast="' + t + '", legenda="' + c + '")'); });
    await T('G1', 'trocar de foto no meio da análise', async () => { await p.setInputFiles('#file', PORT); await sleep(900); await p.setInputFiles('#file', LAND); await p.waitForFunction(() => document.getElementById('capName').textContent === 'montanha.jpg', null, { timeout: 30000 }); await sleep(500); await p.waitForFunction(() => document.getElementById('aiPill').hidden, null, { timeout: 180000 }); await sleep(2500); const n = (await p.locator('#notes li').allTextContents()).join(' '); assert(/céu|montanha/i.test(n), 'notas não são da segunda foto: ' + n.slice(0, 120)); assert(!/pele estava|Pele:/.test(n), 'ficaram notas de pele da primeira foto'); });
    await ctx.close();
  }

  // ---------- G2: looks, automático, ajustar, formato ----------
  if (want('G2')) {
    const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 }, acceptDownloads: true }); const p = await ctx.newPage(); hook(p); await ready(p); await open(p, PORT);
    const base = await sig(p);
    await T('G2', 'cada look muda a foto', async () => { const ids = (await p.$$eval('.look', l => l.map(e => e.dataset.id))).filter(id => id && id !== '+' && !id.startsWith('ref:')); const same = []; let prev = base; for (const id of ids) { await p.click('.look[data-id="' + id + '"]'); await sleep(1700); const s = await sig(p); if (diff(s, prev) < 0.6) same.push(id); prev = s; } await p.click('.look[data-id=""]'); await sleep(1700); const back = await sig(p); assert(same.length === 0, 'sem mudança visível em: ' + same.join(', ')); assert(diff(back, base) < 0.6, 'Sem look não voltou ao automático: ' + diff(back, base).toFixed(2)); return ids.length + ' looks'; });
    await T('G2', 'intensidade do look', async () => { await p.click('.look[data-id="blockbuster"]'); await sleep(1700); const a = await sig(p); await setRange(p, '#lookK', 20); await sleep(1900); const c = await sig(p); assert(diff(a, c) > 0.8, 'diferença ' + diff(a, c).toFixed(2)); return 'diferença ' + diff(a, c).toFixed(1); });
    await T('G2', 'automático desliga e liga', async () => { await p.click('.switch'); await sleep(2200); const off = await sig(p); await p.evaluate(() => document.getElementById('cmpBtn').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }))); await sleep(400); const orig = await sig(p); await p.evaluate(() => document.getElementById('cmpBtn').dispatchEvent(new PointerEvent('pointerup', { bubbles: true }))); await sleep(300); const d0 = diff(off, orig); await p.click('.switch'); await sleep(2600); const on = await sig(p); assert(d0 < 1.5, 'desligado ainda difere do original em ' + d0.toFixed(2)); assert(diff(on, orig) > 0.4, 'ligado não mudou a foto'); return 'desligado difere ' + d0.toFixed(2) + ' | ligado difere ' + diff(on, orig).toFixed(1); });
    await T('G2', 'retoques em 1 toque ligam e desligam', async () => { const out = []; for (const k of ['faceEnh', 'dof', 'skyDeep', 'sharpen']) { const a0 = await p.getAttribute('#quick .chip[data-k="' + k + '"]', 'aria-pressed'); await p.click('#quick .chip[data-k="' + k + '"]'); await sleep(900); const a1 = await p.getAttribute('#quick .chip[data-k="' + k + '"]', 'aria-pressed'); if (a0 === a1) out.push(k + ' não alternou'); await p.click('#quick .chip[data-k="' + k + '"]'); await sleep(500); } assert(!out.length, out.join('; ')); });
    await T('G2', 'Ajustar: os 12 controles mudam a foto', async () => { await tab(p, 'ajustar'); const ks = await p.$$eval('#adjChips .chip', l => l.map(e => e.dataset.k)); const dead = []; for (const k of ks) { await p.click('#adjChips .chip[data-k="' + k + '"]'); await sleep(150); const r = await p.evaluate(() => { const e = document.getElementById('adjRange'); return [+e.min, +e.max]; }); await setRange(p, '#adjRange', r[0]); await sleep(650); const a = await sig(p); await setRange(p, '#adjRange', r[1]); await sleep(650); const c = await sig(p); if (diff(a, c) < 0.5) dead.push(k + '(' + diff(a, c).toFixed(2) + ')'); } await p.click('#adjReset'); await sleep(1200); assert(!dead.length, 'sem efeito visível: ' + dead.join(', ')); return ks.length + ' controles'; });
    await T('G2', 'Formato: proporções batem', async () => { await tab(p, 'formato'); const exp = { feed: 0.8, story: 0.5625, sq: 1, wide: 16 / 9, port: 0.75 }, bad = []; for (const id in exp) { await p.click('.fmt[data-id="' + id + '"]'); await sleep(900); const s = await sig(p), r = s.w / s.h; if (Math.abs(r / exp[id] - 1) > 0.03) bad.push(id + ' deu ' + r.toFixed(3)); } await p.click('.fmt[data-id="orig"]'); await sleep(700); const s = await sig(p); if (Math.abs(s.w / s.h - base.w / base.h) > 0.02) bad.push('Original não voltou'); assert(!bad.length, bad.join('; ')); });
    await T('G2', 'Formato Feed salva em 1080 de largura', async () => { await p.click('.fmt[data-id="feed"]'); await sleep(900); const dl = p.waitForEvent('download', { timeout: 60000 }); await p.click('#saveBtn'); const d = await dl; const f = OUT + '/feed.jpg'; await d.saveAs(f); await p.waitForFunction(() => document.getElementById('finalImg').naturalWidth > 0); const dim = await p.evaluate(() => [document.getElementById('finalImg').naturalWidth, document.getElementById('finalImg').naturalHeight]); assert(dim[0] === 1080 && Math.abs(dim[1] - 1350) <= 2, 'saída ' + dim.join('×')); const b0 = fs.readFileSync(f); assert(b0[0] === 0xFF && b0[1] === 0xD8, 'arquivo não é JPEG'); await p.click('.fmt[data-id="orig"]'); return dim.join('×') + ', ' + Math.round(b0.length / 1024) + ' KB'; });
    await T('G2', 'Girar 90° e Endireitar no Formato', async () => { await sleep(1200); const a = await sig(p); await p.click('#fmtRot'); await sleep(900); const c = await sig(p); assert(Math.abs(c.w / c.h - a.h / a.w) < 0.03, 'não girou: ' + c.w + '×' + c.h); await p.click('#fmtRot'); await p.click('#fmtRot'); await p.click('#fmtRot'); await sleep(900); await p.click('#fmtStraight'); await sleep(900); return await p.innerText('#fmtMsg'); });
    await T('G2', 'comparar mostra o original', async () => { await p.evaluate(() => document.getElementById('cmpBtn').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }))); await sleep(350); const v = await p.isVisible('#flag'); await p.evaluate(() => document.getElementById('cmpBtn').dispatchEvent(new PointerEvent('pointerup', { bubbles: true }))); assert(v, 'etiqueta Original não apareceu'); });
    await T('G2', 'zoom com a roda do mouse', async () => { const bx = await p.locator('#view').boundingBox(); await p.mouse.move(bx.x + bx.width / 2, bx.y + bx.height / 2); await p.mouse.wheel(0, -400); await sleep(300); const t = await p.evaluate(() => document.getElementById('view').style.transform); assert(/scale\((1\.[1-9]|[2-5])/.test(t), 'transform=' + t); await p.mouse.wheel(0, 2000); await sleep(300); const t2 = await p.evaluate(() => document.getElementById('view').style.transform); assert(t2 === '', 'não voltou a 100%: ' + t2); return t; });
    await ctx.close();
  }

  // ---------- G3: ferramentas ----------
  if (want('G3')) {
    const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 }, acceptDownloads: true }); const p = await ctx.newPage(); hook(p); await ready(p); await open(p, PORT);
    const ids = await p.$$eval('.tool[data-tool]', l => l.map(e => e.dataset.tool));
    await T('G3', 'todas as ferramentas abrem e os controles respondem', async () => { const bad = []; for (const id of ids) { const e0 = errs.length; await tool(p, id); const pane = '.toolpane[data-tool="' + id + '"]'; if (!(await p.isVisible(pane))) { bad.push(id + ' não abriu'); continue; } const n = await p.locator(pane + ' input[type=range]').count(); for (let i = 0; i < n; i++) { const r = await p.evaluate(([pane, i]) => { const e = document.querySelectorAll(pane + ' input[type=range]')[i]; const out = []; for (const v of [e.max, e.min]) { e.value = v; e.dispatchEvent(new Event('input', { bubbles: true })); out.push(e.id); } return out[0]; }, [pane, i]); await sleep(120); } await sleep(500); const z = p.locator(pane + ' .linkbtn', { hasText: 'Zerar esta ferramenta' }); if (await z.count()) await z.first().click(); await sleep(250); if (errs.length > e0) bad.push(id + ': ' + errs[e0].slice(0, 90)); } errs.length = 0; assert(!bad.length, bad.join(' | ')); return ids.length + ' ferramentas'; });
    await T('G3', 'Curvas: sugerida, preset e ponto manual', async () => { await tool(p, 'curves'); const a = await sig(p); await p.click('.toolpane[data-tool=curves] .chip:has-text("Contraste")'); await sleep(700); const c = await sig(p); assert(diff(a, c) > 0.5, 'preset sem efeito'); await p.click('.toolpane[data-tool=curves] .chip:has-text("Sugerida")'); await sleep(700); const bx = await p.locator('#curveCv').boundingBox(); await p.mouse.move(bx.x + bx.width * 0.5, bx.y + bx.height * 0.5); await p.mouse.down(); await p.mouse.move(bx.x + bx.width * 0.5, bx.y + bx.height * 0.25, { steps: 5 }); await p.mouse.up(); await sleep(700); const d = await sig(p); assert(diff(c, d) > 0.5, 'arrastar ponto sem efeito'); await p.click('.toolpane[data-tool=curves] .linkbtn:has-text("Zerar")'); await sleep(600); });
    await T('G3', 'Cortar: proporção, arrastar canto, sugerir', async () => { await tool(p, 'crop'); await p.click('.achip[data-a="1:1"]'); await sleep(500); const bx = await p.locator('#view').boundingBox(); await p.mouse.move(bx.x + bx.width * 0.5, bx.y + bx.height * 0.5); await p.mouse.down(); await p.mouse.move(bx.x + bx.width * 0.5, bx.y + bx.height * 0.4, { steps: 5 }); await p.mouse.up(); await sleep(300); await p.click('text=Sugerir corte'); await sleep(500); const m = await p.innerText('#geoMsgC'); await p.click('#toolBack'); await sleep(700); const s = await sig(p); await tool(p, 'crop'); await p.click('.toolpane[data-tool=crop] .linkbtn:has-text("Zerar")'); await p.click('#toolBack'); assert(Math.abs(s.w / s.h - 1) < 0.2, 'corte não é quadrado nem perto: ' + s.w + '×' + s.h); return m; });
    await T('G3', 'Girar: 90°, espelhar, ângulo, endireitar', async () => { await tool(p, 'rotate'); const a = await sig(p); await p.click('.toolpane[data-tool=rotate] .chip:has-text("↻ 90°")'); await sleep(500); const c = await sig(p); assert(Math.abs(c.w / c.h - a.h / a.w) < 0.05, 'não girou'); await p.click('.toolpane[data-tool=rotate] .chip:has-text("Espelhar")'); await sleep(400); await setRange(p, '#geoAngle', 7.5); await sleep(500); await p.click('text=Endireitar automático'); await sleep(700); const m = await p.innerText('#geoMsgR'); await p.click('.toolpane[data-tool=rotate] .linkbtn:has-text("Zerar")'); await p.click('#toolBack'); return m; });
    await T('G3', 'Seletivo: regiões e ponto', async () => { await tool(p, 'selective'); const names = await p.$$eval('#regChips .chip', l => l.map(e => e.textContent)); const res = []; for (const n of names) { await p.click('#regChips .chip:has-text("' + n + '")'); await sleep(250); const note = await p.innerText('#lclNote'); res.push(n + (note ? ' ✗' : ' ✓')); } const cnt = await p.locator('#lyrList .lyr').count(); assert(cnt >= 4, 'só ' + cnt + ' camadas criadas: ' + res.join(' ')); await p.locator('#lyrList .lyr > span').first().click(); await sleep(300); await p.uncheck('#lyMask'); await sleep(500); const a = await sig(p); await setRange(p, '#ly_ev', 1.2); await sleep(700); const c = await sig(p); const bx = await p.locator('#view').boundingBox(); await p.mouse.click(bx.x + bx.width * 0.3, bx.y + bx.height * 0.2); await sleep(600); const cnt2 = await p.locator('#lyrList .lyr').count(); await p.click('.toolpane[data-tool=selective] .linkbtn:has-text("Zerar")'); await sleep(400); assert(diff(a, c) > 0.3, 'ajuste da camada sem efeito'); return res.join(' ') + ' | camadas ' + cnt + '→' + cnt2; });
    await T('G3', 'Pincel: pintar, apagar, desfazer', async () => { await tool(p, 'brush'); await p.check('#lyMask'); const tam = await p.evaluate(() => +document.getElementById('br_size').value); assert(Math.abs(tam - 0.06) < 0.001, 'o controle de tamanho do pincel mostra ' + tam + ' em vez de 0.06'); await sleep(300); const bx = await p.locator('#view').boundingBox(); const stroke = async (y) => { await p.mouse.move(bx.x + bx.width * 0.2, bx.y + bx.height * y); await p.mouse.down(); await p.mouse.move(bx.x + bx.width * 0.8, bx.y + bx.height * y, { steps: 8 }); await p.mouse.up(); await sleep(600); }; const a = await sig(p); await stroke(0.5); const c = await sig(p); assert(diff(a, c) > 0.2, 'traço sem efeito'); await p.click('.modechip[data-k=erase]'); await stroke(0.5); await p.click('.modechip[data-k=paint]'); await stroke(0.7); await p.click('#brUndo'); await sleep(600); const n = await p.locator('#lyrList .lyr').count(); await p.click('.toolpane[data-tool=brush] .linkbtn:has-text("Zerar")'); assert(n >= 1, 'sem camada de pincel'); return n + ' camada(s)'; });
    await T('G3', 'Desfoque de lente e Profundidade: toque na foto', async () => { await tool(p, 'lens'); const bx = await p.locator('#view').boundingBox(); await p.mouse.click(bx.x + bx.width * 0.5, bx.y + bx.height * 0.3); await sleep(700); const v = await p.innerText('.field[data-key=lensBlur] output'); assert(v !== '0%', 'desfoque não ligou: ' + v); await p.click('.toolpane[data-tool=lens] .linkbtn:has-text("Zerar")'); await tool(p, 'depth'); await sleep(400); await p.waitForFunction(() => document.getElementById('aiPill').hidden, null, { timeout: 120000 }); await sleep(300); await p.mouse.click(bx.x + bx.width * 0.5, bx.y + bx.height * 0.3); await sleep(900); const dv = await p.innerText('.field[data-key=dof] output'); assert(dv !== '0%', 'tocar na foto não ligou a profundidade: ' + dv); await p.click('.toolpane[data-tool=depth] .linkbtn:has-text("Zerar")'); return 'lente ' + v + ' | profundidade ' + dv; });
    await T('G3', 'Filtros: os 10 mudam a foto', async () => { await tool(p, 'filters'); const fs2 = await p.$$eval('.fchip', l => l.map(e => e.dataset.f).filter(Boolean)); await p.click('.fchip[data-f=""]'); await sleep(500); const a = await sig(p), dead = []; for (const f of fs2) { await p.click('.fchip[data-f="' + f + '"]'); await sleep(550); const c = await sig(p); if (diff(a, c) < 0.6) dead.push(f); } await setRange(p, '#filterK', 30); await sleep(500); await p.click('.fchip[data-f=""]'); assert(!dead.length, 'sem efeito: ' + dead.join(', ')); return fs2.length + ' filtros'; });
    await T('G3', 'Preto e branco: filtros de cor', async () => { await tool(p, 'bw'); await p.click('.toolpane[data-tool=bw] .chip[data-i="3"]'); await sleep(600); const a = await sig(p); await p.click('.toolpane[data-tool=bw] .chip[data-i="5"]'); await sleep(600); const c = await sig(p); let mx = 0; for (let i = 0; i < a.d.length; i += 4) mx = Math.max(mx, Math.abs(a.d[i] - a.d[i + 1])); await p.click('.toolpane[data-tool=bw] .linkbtn:has-text("Zerar")'); assert(mx < 12, 'não ficou P&B (dif. canais ' + mx + ')'); assert(diff(a, c) > 0.4, 'filtros vermelho e azul iguais'); });
    await T('G3', 'Análise: regiões, sobreposição e refino', async () => { await extraTool(p, 'Análise'); const r = await p.innerText('#regs'); assert(/Cenário/.test(r), 'sem regiões'); const a = await sig(p); await p.check('#ovl'); await sleep(500); const c = await sig(p); await p.uncheck('#ovl'); await p.uncheck('#refine'); await sleep(900); await p.check('#refine'); await sleep(900); assert(diff(a, c) > 1, 'sobreposição sem efeito'); return r.replace(/\n/g, ' ').slice(0, 90); });
    await T('G3', 'Estilo base: 4 estilos', async () => { await extraTool(p, 'Estilo base'); const ks = await p.$$eval('.style', l => l.map(e => e.dataset.key)); let prev = await sig(p); const same = []; for (const k of ks) { await p.click('.style[data-key=' + k + ']'); await sleep(1700); const s = await sig(p); if (diff(s, prev) < 0.3) same.push(k); prev = s; } assert(ks.length === 4, 'estilos: ' + ks.join(',')); return same.length ? 'pouca diferença em: ' + same.join(',') : 'todos distintos'; });
    await T('G3', 'Melhor rosto com 2 fotos', async () => { await extraTool(p, 'Melhor rosto'); const o = fs.readFileSync(CASAL); await p.setInputFiles('#btFiles', [{ name: 'a.jpg', mimeType: 'image/jpeg', buffer: o }, { name: 'b.jpg', mimeType: 'image/jpeg', buffer: o }]); await p.waitForFunction(() => /pessoa|Não/.test(document.getElementById('btMsg').textContent), null, { timeout: 120000 }); const m = await p.innerText('#btMsg'); assert(/pessoa/.test(m), m); await p.click('#btMake'); await p.waitForFunction(() => /Pronto|Nada|base já|Não/.test(document.getElementById('btMsg').textContent), null, { timeout: 120000 }); return m.slice(0, 40) + ' → ' + (await p.innerText('#btMsg')).slice(0, 70); });
    await ctx.close();
  }

  // ---------- G4: IAs sob demanda ----------
  if (want('G4')) {
    const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 }, acceptDownloads: true }); const p = await ctx.newPage(); hook(p); await ready(p); await open(p, PORT);
    const waitAI = () => p.waitForFunction(() => /Pronto em|Cancelado|Não deu|Não achei/.test(document.getElementById('aiSub').textContent), null, { timeout: 600000 });
    await T('G4', 'IA Só fundo + antes/depois + detalhe + força + desfazer', async () => { const t0 = Date.now(); await p.click('#aiFast'); await waitAI(); const m = await p.innerText('#aiSub'); assert(/Pronto em/.test(m), m); const t = Date.now() - t0; await sleep(1500); await p.click('#aiSplit'); await sleep(600); await p.click('#aiSplit'); await p.click('#aiZoom'); await sleep(500); assert(await p.isVisible('#detail'), 'detalhe não abriu'); await p.click('#dClose'); const a = await sig(p); await setRange(p, '#aiStr', 0); await sleep(1500); await p.click('#aiUndo'); await sleep(1500); assert(await p.isHidden('#aiUndo'), 'desfazer continua visível'); return t + ' ms'; });
    await T('G4', 'IA Só rostos em retrato', async () => { const t0 = Date.now(); await p.click('#aiFace'); await waitAI(); const m = await p.innerText('#aiSub'); assert(/rosto restaurado|rostos restaurados/.test(m), m); await sleep(1200); await p.click('#aiUndo'); await sleep(1200); return (Date.now() - t0) + ' ms'; });
    await T('G4', 'cancelar a IA no meio', async () => { await p.click('#aiBest'); await p.waitForFunction(() => !document.getElementById('loading').hidden); await sleep(2500); await p.click('#ldCancel'); await waitAI(); const m = await p.innerText('#aiSub'); assert(/Cancelado/.test(m), m); assert(await p.isHidden('#loading'), 'tela de espera ficou aberta'); });
    await T('G4', 'IA Só rostos em paisagem avisa que não há rosto', async () => { await open(p, LAND); await p.click('#aiFace'); await waitAI(); const m = await p.innerText('#aiSub'); assert(/Não achei rosto/.test(m), m); });
    await T('G4', 'salvar depois da IA gera JPEG válido', async () => { const dl = p.waitForEvent('download', { timeout: 90000 }); await p.click('#saveBtn'); const d = await dl; const f = OUT + '/save.jpg'; await d.saveAs(f); const b0 = fs.readFileSync(f); assert(b0[0] === 0xFF && b0[1] === 0xD8 && b0.length > 20000, 'arquivo inválido ' + b0.length); await p.waitForFunction(() => document.getElementById('finalImg').naturalWidth > 0); return await p.evaluate(() => document.getElementById('finalImg').naturalWidth + '×' + document.getElementById('finalImg').naturalHeight) + ', ' + Math.round(b0.length / 1024) + ' KB'; });
    await ctx.close();
  }

  // ---------- G5: celular ----------
  if (want('G5')) {
    const ctx = await b.newContext({ viewport: { width: 360, height: 760 }, deviceScaleFactor: 2, hasTouch: true, isMobile: true, acceptDownloads: true, userAgent: 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/126 Mobile Safari/537.36' }); const p = await ctx.newPage(); hook(p); await ready(p);
    const over = () => p.evaluate(() => document.documentElement.scrollWidth - innerWidth);
    await T('G5', 'tela inicial cabe em 360×760', async () => { const o = await over(); await p.screenshot({ path: OUT + '/m_inicio.png' }); assert(o <= 0, 'rola de lado ' + o + 'px'); const v = await p.evaluate(() => { const r = document.getElementById('galBtn').getBoundingClientRect(); return r.bottom <= innerHeight && r.top >= 0; }); assert(v, 'botão da galeria fora da tela'); });
    await open(p, PORT);
    await T('G5', 'área da foto no celular', async () => { const r = await p.evaluate(() => { const v = document.getElementById('view').getBoundingClientRect(), pn = document.querySelector('.panel').getBoundingClientRect(); return { fotoAlt: Math.round(v.height), fotoLarg: Math.round(v.width), tela: innerHeight, painel: Math.round(pn.height) }; }); await p.screenshot({ path: OUT + '/m_foto.png' }); assert(r.fotoAlt / r.tela >= 0.42, 'a foto ocupa só ' + Math.round(r.fotoAlt / r.tela * 100) + '% da altura (' + r.fotoAlt + ' de ' + r.tela + ' px), painel ' + r.painel + ' px'); return JSON.stringify(r); });
    await T('G5', 'nenhuma aba rola de lado', async () => { const bad = []; for (const t of ['looks', 'ajustar', 'formato', 'ferramentas']) { await p.tap('.tabbtn[data-tab=' + t + ']'); await sleep(350); const o = await over(); if (o > 0) bad.push(t + ' +' + o + 'px'); } const ids = await p.$$eval('.tool[data-tool]', l => l.map(e => e.dataset.tool)); for (const id of ids) { await p.tap('.tool[data-tool=' + id + ']'); await sleep(200); const o = await over(); if (o > 0) bad.push('ferramenta ' + id + ' +' + o + 'px'); await p.tap('#toolBack'); await sleep(120); } assert(!bad.length, bad.join('; ')); });
    await T('G5', 'alvos de toque com pelo menos 40 px', async () => { await p.tap('.tabbtn[data-tab=looks]'); await sleep(300); const small = await p.evaluate(() => { const out = []; for (const sel of ['.top .btn', '.tabbtn', '#quick .chip', '.switch', '#aiBox .chip', '#barsChip']) for (const e of document.querySelectorAll(sel)) { const r = e.getBoundingClientRect(); if (r.width > 0 && (r.height < 40 || r.width < 40)) out.push(sel + ' "' + e.textContent.trim().slice(0, 14) + '" ' + Math.round(r.width) + '×' + Math.round(r.height)); } return out; }); assert(!small.length, small.slice(0, 8).join('; ')); });
    const semZoom = async () => { await p.evaluate(() => { if (document.getElementById('view').style.transform) window.revelaBack(); }); await sleep(250); };
    const escala = () => p.evaluate(() => parseFloat((document.getElementById('view').style.transform.match(/scale\(([\d.]+)\)/) || [0, '1'])[1]));
    const pinca = async (cx, cy) => { const cdp = await ctx.newCDPSession(p); const pts = d => [{ x: cx - d, y: cy, id: 0 }, { x: cx + d, y: cy, id: 1 }]; await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: pts(30) }); for (const d of [45, 60, 80, 100]) { await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: pts(d) }); await sleep(40); } await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(500); await cdp.detach(); };
    await T('G5', 'toque duplo dá zoom e volta', async () => { await semZoom(); const bx = await p.locator('#view').boundingBox(), x = bx.x + bx.width * 0.5, y = bx.y + bx.height * 0.4; await p.touchscreen.tap(x, y); await sleep(110); await p.touchscreen.tap(x, y); await sleep(400); const e1 = await escala(); assert(Math.abs(e1 - 2.5) < 0.01, 'escala ' + e1); await p.touchscreen.tap(x, y); await sleep(110); await p.touchscreen.tap(x, y); await sleep(400); const e2 = await escala(); assert(e2 === 1, 'não voltou: ' + e2); });
    await T('G5', 'pinça dá zoom e o zoom fica depois de soltar os dedos', async () => { await semZoom(); const bx = await p.locator('#view').boundingBox(); await pinca(bx.x + bx.width / 2, bx.y + bx.height / 2); const e = await escala(), r = await p.evaluate(() => ({ vv: visualViewport.scale, abas: document.querySelector('.tabs').getBoundingClientRect().bottom <= innerHeight + 1, topo: document.querySelector('.top').getBoundingClientRect().height })); await p.screenshot({ path: OUT + '/m_zoom.png' }); assert(e > 2.5, 'escala depois de soltar: ' + e); assert(r.vv === 1, 'a página inteira deu zoom: ' + r.vv); assert(r.abas, 'a barra de abas saiu da tela'); return 'escala ' + e.toFixed(2); });
    await T('G5', 'com zoom, um dedo arrasta a foto', async () => { const cdp = await ctx.newCDPSession(p); const w = await p.locator('#wrap').boundingBox(), x = w.x + w.width / 2, y = w.y + w.height / 2; const t0 = await p.evaluate(() => document.getElementById('view').style.transform); await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y, id: 0 }] }); for (const d of [15, 30, 45, 60]) { await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - d, y: y - d / 2, id: 0 }] }); await sleep(30); } await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(300); await cdp.detach(); const t1 = await p.evaluate(() => document.getElementById('view').style.transform); assert(t0 !== t1 && /scale/.test(t1), 'não arrastou: ' + t0 + ' -> ' + t1); assert(await p.isHidden('#flag'), 'arrastar mostrou o Original'); });
    await T('G5', 'pinça no painel não amplia a página inteira', async () => { const pn = await p.locator('.panes').boundingBox(); await pinca(pn.x + pn.width / 2, pn.y + pn.height / 2); const vv = await p.evaluate(() => visualViewport.scale); assert(vv === 1, 'a página ampliou para ' + vv); });
    await T('G5', 'botão Voltar: desfaz zoom, fecha ferramenta, volta de aba e avisa antes de sair', async () => { const r1 = await p.evaluate(() => window.revelaBack()); assert(r1 === true && (await escala()) === 1, 'não desfez o zoom'); await p.tap('.tabbtn[data-tab=ferramentas]'); await p.tap('.tool[data-tool=adjust]'); await sleep(300); const r2 = await p.evaluate(() => window.revelaBack()); assert(r2 === true && await p.isVisible('#toolList'), 'não fechou a ferramenta'); const r3 = await p.evaluate(() => window.revelaBack()); assert(r3 === true && (await p.getAttribute('.tabbtn[data-tab=looks]', 'aria-selected')) === 'true', 'não voltou para Looks'); const r4 = await p.evaluate(() => window.revelaBack()); const t = await p.innerText('#toast'); assert(r4 === true && /Voltar de novo/.test(t), 'sem aviso antes de sair: ' + t); const r5 = await p.evaluate(() => window.revelaBack()); assert(r5 === false, 'o segundo Voltar deveria liberar a saída'); });
    await T('G5', 'segurar na foto mostra o original', async () => { await p.evaluate(() => { const v = document.getElementById('view'); v.dispatchEvent(new WheelEvent('wheel', { deltaY: 9000, bubbles: true, cancelable: true, clientX: 100, clientY: 200 })); }); await sleep(300); const cdp = await ctx.newCDPSession(p); const bx = await p.locator('#view').boundingBox(); const pt = [{ x: bx.x + bx.width / 2, y: bx.y + bx.height / 2, id: 0 }]; await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: pt }); await sleep(700); const v = await p.isVisible('#flag'); await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await sleep(300); const v2 = await p.isVisible('#flag'); assert(v, 'não mostrou o original ao segurar'); assert(!v2, 'ficou preso no original depois de soltar'); });
    await T('G5', 'ferramenta aberta: a foto continua visível e o painel rola', async () => { await p.tap('.tabbtn[data-tab=ferramentas]'); await p.tap('.tool[data-tool=adjust]'); await sleep(400); await p.screenshot({ path: OUT + '/m_ajustar.png' }); const r = await p.evaluate(() => { const v = document.getElementById('view').getBoundingClientRect(), ps = document.querySelector('.panes'); return { foto: Math.round(v.height), rola: ps.scrollHeight > ps.clientHeight, visiveis: [...document.querySelectorAll('.toolpane[data-tool=adjust] .field')].filter(f => { const r = f.getBoundingClientRect(); return r.top >= 0 && r.bottom <= innerHeight - 60; }).length }; }); await p.tap('#toolBack'); assert(r.visiveis >= 3, 'só ' + r.visiveis + ' controles visíveis sem rolar'); return JSON.stringify(r); });
    await T('G5', 'salvar no navegador do celular', async () => { await p.tap('.tabbtn[data-tab=looks]'); const dl = p.waitForEvent('download', { timeout: 60000 }).catch(() => null); await p.tap('#saveBtn'); const d = await dl; const t = await p.innerText('#toast'); await sleep(800); await p.screenshot({ path: OUT + '/m_salvo.png' }); assert(d, 'sem download; aviso: ' + t); return t; });
    await ctx.close();
  }

  // ---------- G7: IA Revela (rede própria do app) ----------
  if (want('G7')) {
    const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 }, acceptDownloads: true }); const p = await ctx.newPage(); hook(p); await ready(p);
    const orig = async () => { await p.evaluate(() => document.getElementById('cmpBtn').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true }))); await sleep(450); const s = await sig(p); await p.evaluate(() => document.getElementById('cmpBtn').dispatchEvent(new PointerEvent('pointerup', { bubbles: true }))); await sleep(450); return s; };
    const med = (s, f) => { let t = 0; for (let i = 0; i < s.d.length; i += 4) t += f(s.d[i], s.d[i + 1], s.d[i + 2]); return t / (s.d.length / 4); };
    const luz = s => med(s, (r, g, b2) => 0.2126 * r + 0.7152 * g + 0.0722 * b2), cor = s => med(s, (r, g, b2) => Math.max(r, g, b2) - Math.min(r, g, b2)), calor = s => med(s, (r, g, b2) => r - b2);
    const estragada = (file, filtro, tinta) => p.evaluate(async ([b64, filtro, tinta]) => { const img = new Image(); img.src = 'data:image/jpeg;base64,' + b64; await img.decode(); const c = document.createElement('canvas'), k = Math.min(1, 1200 / Math.max(img.width, img.height)); c.width = Math.round(img.width * k); c.height = Math.round(img.height * k); const x = c.getContext('2d'); x.filter = filtro || 'none'; x.drawImage(img, 0, 0, c.width, c.height); x.filter = 'none'; if (tinta) { x.globalCompositeOperation = 'multiply'; x.fillStyle = tinta; x.fillRect(0, 0, c.width, c.height); } return c.toDataURL('image/jpeg', 0.92).split(',')[1]; }, [fs.readFileSync(file).toString('base64'), filtro, tinta]);
    const abrir = async (nome, file, filtro, tinta) => open(p, { name: nome, mimeType: 'image/jpeg', buffer: Buffer.from(await estragada(file, filtro, tinta), 'base64') });
    await T('G7', 'IA Revela é o motor padrão, roda no aparelho e é rápida', async () => { await open(p, SP + '/images/1.jpg'); const r = await p.evaluate(() => ({ h: document.getElementById('heroT').textContent, ms: window.__tm.tom, np: (window.__tm.tomP || []).length, linha: !document.getElementById('tomRow').hidden, nota: (document.querySelector('#notes li') || {}).textContent || '', ia: document.getElementById('motorIa').getAttribute('aria-pressed') })); assert(/Melhorada pela IA Revela/.test(r.h), 'hero: ' + r.h); assert(r.np === 62 && r.ms < 1500, 'parâmetros ' + r.np + ', tempo ' + r.ms + ' ms'); assert(r.linha && r.ia === 'true' && /^IA Revela/.test(r.nota), 'tela não mostra a IA: ' + JSON.stringify(r).slice(0, 160)); return r.ms + ' ms'; });
    await T('G7', 'foto escura e lavada: a IA clareia, dá contraste e cor', async () => { await abrir('escura.jpg', LAND, 'brightness(0.55) contrast(0.7) saturate(0.6)'); const a = await orig(), c = await sig(p); assert(luz(c) > luz(a) + 6, 'luz ' + luz(a).toFixed(1) + ' -> ' + luz(c).toFixed(1)); assert(cor(c) > cor(a) * 1.15, 'cor ' + cor(a).toFixed(1) + ' -> ' + cor(c).toFixed(1)); return 'luz ' + luz(a).toFixed(0) + ' -> ' + luz(c).toFixed(0) + ' | cor ' + cor(a).toFixed(0) + ' -> ' + cor(c).toFixed(0); });
    await T('G7', 'foto amarelada: a IA não piora a dominante (corrigir de verdade é limite conhecido da v0)', async () => { await abrir('amarela.jpg', LAND, null, '#ffd79a'); const a = await orig(), c = await sig(p); assert(calor(c) < calor(a) * 1.6 + 2, 'a dominante aumentou demais: ' + calor(a).toFixed(1) + ' -> ' + calor(c).toFixed(1)); return 'vermelho menos azul ' + calor(a).toFixed(0) + ' -> ' + calor(c).toFixed(0) + ' (a rede quase não desfaz a tinta)'; });
    await T('G7', 'retrato amarelado em ambiente interno: a cor da pele corrige a foto', async () => { await abrir('casal_amarelo.jpg', CASAL, null, '#ffd79a'); const a = await orig(), c = await sig(p); const nota = (await p.locator('#notes li').allTextContents()).find(t => /amarelad/.test(t)) || ''; assert(calor(c) < calor(a) - 6, 'calor ' + calor(a).toFixed(1) + ' -> ' + calor(c).toFixed(1)); assert(nota, 'sem explicação nas notas'); return 'vermelho menos azul ' + calor(a).toFixed(0) + ' -> ' + calor(c).toFixed(0); });
    await T('G7', 'foto estourada e sem contraste: a IA escurece e firma os pretos', async () => { await abrir('clara.jpg', LAND, 'brightness(1.35) contrast(0.75)'); const a = await orig(), c = await sig(p); assert(luz(c) < luz(a) - 4, 'luz ' + luz(a).toFixed(1) + ' -> ' + luz(c).toFixed(1)); return 'luz ' + luz(a).toFixed(0) + ' -> ' + luz(c).toFixed(0); });
    await T('G7', 'foto já bem tratada quase não muda', async () => { await open(p, LAND); const a = await orig(), c = await sig(p); assert(Math.abs(luz(c) - luz(a)) < 8 && diff(a, c) < 9, 'luz ' + luz(a).toFixed(1) + ' -> ' + luz(c).toFixed(1) + ', diferença ' + diff(a, c).toFixed(1)); return 'diferença média ' + diff(a, c).toFixed(1) + ' de 255'; });
    await T('G7', 'Força da IA: 0% tira a correção, 150% reforça', async () => { await abrir('escura.jpg', LAND, 'brightness(0.55) contrast(0.7) saturate(0.6)'); const c100 = await sig(p); await setRange(p, '#tomK', 0); await sleep(900); const c0 = await sig(p); await setRange(p, '#tomK', 150); await sleep(900); const c150 = await sig(p); await setRange(p, '#tomK', 100); await sleep(700); assert(luz(c0) < luz(c100) - 4 && luz(c150) > luz(c100) + 2, 'luz 0%=' + luz(c0).toFixed(1) + ' 100%=' + luz(c100).toFixed(1) + ' 150%=' + luz(c150).toFixed(1)); return 'luz 0% ' + luz(c0).toFixed(0) + ' | 100% ' + luz(c100).toFixed(0) + ' | 150% ' + luz(c150).toFixed(0); });
    await T('G7', 'motor clássico e de volta para a IA', async () => { const ia = await sig(p); await p.click('#motorRg'); await sleep(3200); const h1 = await p.innerText('#heroT'), cl = await sig(p); await p.click('#motorIa'); await sleep(1500); const h2 = await p.innerText('#heroT'), ia2 = await sig(p); assert(/clássico/.test(h1) && /IA Revela/.test(h2), h1 + ' / ' + h2); assert(await p.isHidden('#tomRow') === false, 'controle de força sumiu'); assert(diff(ia, ia2) < 0.8, 'voltar para a IA não reproduziu o resultado: ' + diff(ia, ia2).toFixed(2)); return 'clássico difere da IA em ' + diff(ia, cl).toFixed(1); });
    await T('G7', 'a foto salva sai com a correção da IA', async () => { const dl = p.waitForEvent('download', { timeout: 60000 }); await p.click('#saveBtn'); await dl; await p.waitForFunction(() => document.getElementById('finalImg').naturalWidth > 0); const v = await sigEl(p, '#view'), f = await sigEl(p, '#finalImg'); assert(diff(v, f) < 3, 'arquivo salvo difere da tela em ' + diff(v, f).toFixed(1)); return 'diferença tela x arquivo ' + diff(v, f).toFixed(1); });
    await T('G7', 'look por cima da IA e intensidade do look', async () => { const a = await sig(p); await p.click('.look[data-id="blockbuster"]'); await sleep(1500); const h = await p.innerText('#heroT'), c = await sig(p); await p.click('.look[data-id=""]'); await sleep(1200); assert(/sobre a IA Revela/.test(h) && diff(a, c) > 1, h + ' | diferença ' + diff(a, c).toFixed(1)); });
    await T('G7', 'a escolha do motor fica guardada', async () => { await p.click('#motorRg'); await sleep(500); await p.reload(); await sleep(2500); const r = await p.getAttribute('#motorRg', 'aria-pressed'); await p.click('#motorIa'); await sleep(300); assert(r === 'true', 'voltou para a IA depois de recarregar'); });
    await ctx.close();
  }

  // ---------- G8: copiar o look de uma foto de referência ----------
  if (want('G8')) {
    const ctx = await b.newContext({ viewport: { width: 1400, height: 1000 }, acceptDownloads: true }); const p = await ctx.newPage(); hook(p); await ready(p);
    const FOTO = SP + '/images/barba.jpg', REF = SP + '/images/barba_gpt.png', PB = SP + '/pexels/homem_barba.jpg';
    const med = (s, f) => { let t = 0; for (let i = 0; i < s.d.length; i += 4) t += f(s.d[i], s.d[i + 1], s.d[i + 2]); return t / (s.d.length / 4); };
    const luz = s => med(s, (r, g, b2) => 0.2126 * r + 0.7152 * g + 0.0722 * b2), cor = s => med(s, (r, g, b2) => Math.max(r, g, b2) - Math.min(r, g, b2));
    const sigArq = file => p.evaluate(async ([b64, mime]) => { const img = new Image(); img.src = 'data:' + mime + ';base64,' + b64; await img.decode(); const c = document.createElement('canvas'); c.width = 240; c.height = 240; const x = c.getContext('2d'); x.imageSmoothingQuality = 'high'; x.drawImage(img, 0, 0, 240, 240); const d = x.getImageData(0, 0, 240, 240).data, out = []; for (let by = 0; by < 24; by++) for (let bx = 0; bx < 24; bx++) { let r = 0, g = 0, b = 0; for (let y = 0; y < 10; y++) for (let xx = 0; xx < 10; xx++) { const i = ((by * 10 + y) * 240 + bx * 10 + xx) * 4; r += d[i]; g += d[i + 1]; b += d[i + 2]; } out.push(r / 100, g / 100, b / 100, 255); } return { d: out }; }, [fs.readFileSync(file).toString('base64'), /png$/i.test(file) ? 'image/png' : 'image/jpeg']);
    const copiar = async file => { const n0 = await p.locator('.look.ref').count(); await p.setInputFiles('#refFile', file); await p.waitForFunction(n => document.querySelectorAll('.look.ref').length > n || /Look copiado/.test(document.getElementById('heroT').textContent), n0, { timeout: 20000 }); await sleep(1800); };
    await T('G8', 'cartão Copiar look aparece logo depois de Sem look', async () => { const ids = await p.$$eval('.look', l => l.map(e => e.dataset.id)); assert(ids[0] === '' && ids[1] === '+', 'ordem: ' + ids.slice(0, 3).join(' | ')); });
    await open(p, FOTO);
    const semLook = await sigEl(p, '#view'), alvo = await sigArq(REF);
    await T('G8', 'copiar o look aproxima luz e cor da referência', async () => { await copiar(REF); const h = await p.innerText('#heroT'), com = await sigEl(p, '#view'); assert(/Look copiado/.test(h), 'hero: ' + h); const dl0 = Math.abs(luz(semLook) - luz(alvo)), dl1 = Math.abs(luz(com) - luz(alvo)), dc0 = Math.abs(cor(semLook) - cor(alvo)), dc1 = Math.abs(cor(com) - cor(alvo)); assert(dl1 < dl0 * 0.6 + 1 && dc1 < dc0 * 0.5 + 1, 'luz ' + dl0.toFixed(1) + '->' + dl1.toFixed(1) + ' | cor ' + dc0.toFixed(1) + '->' + dc1.toFixed(1)); return 'distância até a referência: luz ' + dl0.toFixed(1) + ' -> ' + dl1.toFixed(1) + ' | cor ' + dc0.toFixed(1) + ' -> ' + dc1.toFixed(1); });
    await T('G8', 'intensidade do look copiado: 0% volta ao automático', async () => { const c100 = await sigEl(p, '#view'); await setRange(p, '#lookK', 0); await sleep(1200); const c0 = await sigEl(p, '#view'); await setRange(p, '#lookK', 100); await sleep(1200); const c100b = await sigEl(p, '#view'); assert(diff(c0, semLook) < 1.2, '0% difere do automático em ' + diff(c0, semLook).toFixed(2)); assert(diff(c100, c0) > 3 && diff(c100, c100b) < 0.8, '100% x 0%: ' + diff(c100, c0).toFixed(2)); return '0% difere do automático em ' + diff(c0, semLook).toFixed(2) + ' | 100% difere em ' + diff(c100, c0).toFixed(1); });
    await T('G8', 'a foto salva sai com o look copiado', async () => { const dl = p.waitForEvent('download', { timeout: 60000 }); await p.click('#saveBtn'); await dl; await p.waitForFunction(() => document.getElementById('finalImg').naturalWidth > 0); const v = await sigEl(p, '#view'), f = await sigEl(p, '#finalImg'); assert(diff(v, f) < 3, 'arquivo difere da tela em ' + diff(v, f).toFixed(1)); return 'diferença tela x arquivo ' + diff(v, f).toFixed(1); });
    await T('G8', 'o look fica guardado e vale para outra foto', async () => { await p.reload(); await sleep(2500); await p.waitForFunction(() => /pronta|indispon/.test(document.getElementById('segStat').textContent), null, { timeout: 90000 }); const n = await p.locator('.look.ref').count(); assert(n === 1, 'guardados depois de recarregar: ' + n); await open(p, PORT); const a = await sigEl(p, '#view'); await p.click('.look.ref'); await sleep(1800); const h = await p.innerText('#heroT'), c = await sigEl(p, '#view'); assert(/Look copiado/.test(h) && diff(a, c) > 2, h + ' | diferença ' + diff(a, c).toFixed(1)); return (await p.locator('.look.ref span').first().innerText()) + ' aplicado em outra foto, diferença ' + diff(a, c).toFixed(1); });
    await T('G8', 'referência em preto e branco tira a cor da foto', async () => { await copiar(PB); const c = await sigEl(p, '#view'); assert(cor(c) < 4, 'cor média ' + cor(c).toFixed(1)); return 'cor média ' + cor(c).toFixed(1) + ' de 255'; });
    await T('G8', 'o rosto não estoura com look de foto muito diferente', async () => { await p.click('.look.ref'); await sleep(1500); const r = await p.evaluate(() => { const v = document.getElementById('view'), x = v.getContext('2d'), d = x.getImageData(0, 0, v.width, v.height).data; let n = 0, est = 0; for (let i = 0; i < d.length; i += 16) { n++; if (d[i] > 250 && d[i + 1] > 250 && d[i + 2] > 250) est++; } return est / n; }); assert(r < 0.06, Math.round(r * 100) + '% da foto estourada'); return Math.round(r * 1000) / 10 + '% de pixels estourados'; });
    await T('G8', 'apagar um look copiado', async () => { const n0 = await p.locator('.look.ref').count(); await p.locator('.look.ref .del').first().click(); await sleep(900); const n1 = await p.locator('.look.ref').count(), h = await p.innerText('#heroT'); assert(n1 === n0 - 1, n0 + ' -> ' + n1); assert(!/Look copiado/.test(h) || n1 > 0, 'look apagado continua ativo: ' + h); await p.locator('.look.ref .del').first().click().catch(() => {}); await sleep(500); return n0 + ' -> ' + n1; });
    await T('G8', 'referência que não é foto dá aviso', async () => { await p.setInputFiles('#refFile', { name: 'nota.txt', mimeType: 'text/plain', buffer: Buffer.from('oi') }); await sleep(600); const t = await p.evaluate(() => document.getElementById('toast').textContent); assert(/Escolha uma foto|Não consegui/.test(t), 'aviso: ' + t); });
    await ctx.close();
  }

  // ---------- G6: PWA e offline ----------
  if (want('G6')) {
    const ctx = await b.newContext({ viewport: { width: 390, height: 844 } }); const p = await ctx.newPage(); hook(p);
    await T('G6', 'service worker guarda o app e os modelos', async () => { await p.goto(URL); await sleep(14000); const r = await p.evaluate(async () => { const reg = await navigator.serviceWorker.getRegistration(); const ks = await caches.keys(); const urls = ks.length ? (await (await caches.open(ks[ks.length - 1])).keys()).map(x => x.url) : []; return { reg: !!reg, cache: ks.join(','), n: urls.length, modelos: urls.filter(u => /vendor\//.test(u)).length, iso: self.crossOriginIsolated }; }); assert(r.reg && r.modelos >= 10, JSON.stringify(r)); return JSON.stringify(r); });
    await T('G6', 'funciona sem internet depois da primeira visita', async () => { await ctx.setOffline(true); await p.reload(); await sleep(2500); await p.waitForFunction(() => /pronta|indispon/.test(document.getElementById('segStat').textContent), null, { timeout: 90000 }); const st = await p.innerText('#segStat'); assert(/pronta/.test(st), st); await open(p, PORT); const h = await p.innerText('#heroT'); const sc = (await p.locator('#notes li').allTextContents()).join(' '); assert(/IA Revela/.test(h), 'a IA Revela não rodou sem internet: ' + h); assert(/reconheci/.test(sc), 'a IA de cena não rodou sem internet'); await ctx.setOffline(false); return h; });
    await ctx.close();
  }

  await b.close();
  fs.writeFileSync(OUT + '/suite.json', JSON.stringify(R, null, 1));
  const f = R.filter(r => !r.ok);
  console.log('\n===== ' + R.length + ' testes, ' + (R.length - f.length) + ' passaram, ' + f.length + ' falharam =====');
  for (const r of f) console.log(' - [' + r.group + '] ' + r.name + ': ' + r.info);
})().catch(e => { console.log('SUITE QUEBROU', e); process.exit(1); });
